export const roomLayouts = [
  {
    id: 1,
    name: "Almacén en L - Zona de Entrada",
    description: "Forma de L con pasillo estrecho y sala amplia. Tutorial de movimiento y primeras coberturas",
    playerStart: { x: 2, y: 2 },
    exit: { x: 38, y: 28 },
    walls: [
      { x: 0, y: 0, width: 25, height: 1 },
      { x: 0, y: 0, width: 1, height: 15 },
      { x: 0, y: 14, width: 15, height: 1 },
      { x: 14, y: 14, width: 1, height: 16 },
      { x: 14, y: 29, width: 26, height: 1 },
      { x: 39, y: 0, width: 1, height: 30 },
      { x: 24, y: 0, width: 16, height: 1 }
    ],
    objects: [
      { id: '1', name: 'Estanteria alta con comida 1', type: 'wall', x: 2, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '2', name: 'Estanteria alta con comida 2', type: 'wall', x: 8, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '3', name: 'Estanteria alta con comida 3', type: 'wall', x: 14, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '4', name: 'Estanteria metalica vacia', type: 'wall', x: 20, y: 1, width: 3, height: 1.5, category: 'furniture' },
      { id: '5', name: 'Palés apoyados a la pared', type: 'wall', x: 1, y: 10, width: 2, height: 1.5, category: 'furniture' },
      { id: '6', name: 'Tuberias vistas en la pared', type: 'wall', x: 38, y: 2, width: 1, height: 8, category: 'structure' },
      { id: '7', name: 'Cuadros Electricos', type: 'wall', x: 38, y: 12, width: 1, height: 2, category: 'structure' },
      { id: '8', name: 'Extintor con Soporte', type: 'wall', x: 1, y: 6, width: 0.8, height: 1, category: 'prop' },
      { id: '9', name: 'Señales de seguridad', type: 'wall', x: 12, y: 1, width: 1, height: 0.8, category: 'prop' },
      { id: '10', name: 'Puerta metalica de carga', type: 'wall', x: 38, y: 26, width: 1, height: 3, category: 'door' },
      { id: '11', name: 'Ventana alta pequeña con barrotes', type: 'wall', x: 26, y: 0.2, width: 2, height: 0.8, category: 'structure' },
      { id: '12', name: 'Columna hormigon sucios 1', type: 'wall', x: 10, y: 7, width: 2, height: 2, category: 'structure' },
      { id: '13', name: 'Caja carton vacia 1', type: 'floor', x: 4, y: 5, width: 1.5, height: 1.5, category: 'cover' },
      { id: '14', name: 'Caja carton vacia 2', type: 'floor', x: 6, y: 5.5, width: 1.5, height: 1.5, category: 'cover' },
      { id: '15', name: 'Caja carton vacia 3', type: 'floor', x: 5, y: 7, width: 1.5, height: 1.5, category: 'cover' },
      { id: '16', name: 'Pales madera apilados', type: 'floor', x: 16, y: 16, width: 3, height: 3, category: 'cover' },
      { id: '17', name: 'carretilla de mano', type: 'floor', x: 20, y: 18, width: 1.2, height: 1.8, category: 'obstacle' },
      { id: '18', name: 'transpaleta manual', type: 'floor', x: 22, y: 16, width: 1, height: 2.5, category: 'obstacle' },
      { id: '19', name: 'barriles / bidones', type: 'floor', x: 25, y: 17, width: 2.5, height: 2.5, category: 'cover' },
      { id: '20', name: 'Sacos harina', type: 'floor', x: 29, y: 16, width: 2, height: 2.5, category: 'cover' },
      { id: '21', name: 'Sacos azucar', type: 'floor', x: 32, y: 16, width: 2, height: 2.5, category: 'cover' },
      { id: '22', name: 'Monton de cajas', type: 'floor', x: 28, y: 6, width: 3.5, height: 3, category: 'cover' },
      { id: '23', name: 'Carros de almacen', type: 'floor', x: 33, y: 8, width: 2, height: 1.5, category: 'obstacle' },
      { id: '24', name: 'Charcos de liquido', type: 'structure', x: 18, y: 23, width: 3, height: 1.5, category: 'hazard' },
      { id: '25', name: 'Trozos pequeños de papel', type: 'structure', x: 24, y: 25, width: 2, height: 1, category: 'detail' },
      { id: '26', name: 'Suelo sucio 1', type: 'structure', x: 6, y: 10, width: 4, height: 3, category: 'floor_detail' },
      { id: '27', name: 'Suelo sucio 2', type: 'structure', x: 26, y: 22, width: 5, height: 4, category: 'floor_detail' },
      { id: '28', name: 'Suelo sucio 3', type: 'structure', x: 15, y: 19, width: 3, height: 2, category: 'floor_detail' },
      { id: '29', name: 'Pared sucia 1', type: 'structure', x: 1, y: 3, width: 0.5, height: 2, category: 'wall_detail' },
      { id: '30', name: 'Pared sucia 2', type: 'structure', x: 14.5, y: 16, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '31', name: 'Pared sucia 3', type: 'structure', x: 38, y: 15, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '32', name: 'Lampara industrial 1', type: 'structure', x: 8, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '33', name: 'Lampara industrial 2', type: 'structure', x: 20, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '34', name: 'Lampara industrial 3', type: 'structure', x: 25, y: 20, width: 1.5, height: 0.7, category: 'lighting' }
    ],
    enemies: [{ x: 12, y: 9, type: 'ranged' }]
  },
  {
    id: 2,
    name: "Pasillo Zigzag con Recodos",
    description: "Corredor en zigzag con múltiples esquinas y emboscadas. Aprender a usar coberturas",
    playerStart: { x: 2, y: 2 },
    exit: { x: 38, y: 28 },
    walls: [
      { x: 0, y: 0, width: 12, height: 1 },
      { x: 0, y: 0, width: 1, height: 12 },
      { x: 0, y: 11, width: 8, height: 1 },
      { x: 7, y: 11, width: 1, height: 8 },
      { x: 7, y: 18, width: 13, height: 1 },
      { x: 19, y: 7, width: 1, height: 12 },
      { x: 19, y: 7, width: 10, height: 1 },
      { x: 28, y: 7, width: 1, height: 13 },
      { x: 28, y: 19, width: 12, height: 1 },
      { x: 39, y: 0, width: 1, height: 30 },
      { x: 11, y: 0, width: 29, height: 1 }
    ],
    objects: [
      { id: '35', name: 'Estanteria alta con comida 1', type: 'wall', x: 2, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '36', name: 'Estanteria alta con comida 2', type: 'wall', x: 20, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '37', name: 'Estanteria alta con comida 3', type: 'wall', x: 8, y: 12, width: 4, height: 1.5, category: 'furniture' },
      { id: '38', name: 'Estanteria metalica vacia', type: 'wall', x: 29, y: 8, width: 4, height: 1.5, category: 'furniture' },
      { id: '39', name: 'Palés apoyados a la pared', type: 'wall', x: 1, y: 7, width: 2, height: 1.5, category: 'furniture' },
      { id: '40', name: 'Tuberias vistas en la pared', type: 'wall', x: 7.2, y: 13, width: 0.8, height: 5, category: 'structure' },
      { id: '41', name: 'Cuadros Electricos', type: 'wall', x: 19.2, y: 9, width: 0.8, height: 2.5, category: 'structure' },
      { id: '42', name: 'Extintor con Soporte', type: 'wall', x: 28.2, y: 12, width: 0.8, height: 1.2, category: 'prop' },
      { id: '43', name: 'Señales de seguridad', type: 'wall', x: 15, y: 1, width: 1.2, height: 0.8, category: 'prop' },
      { id: '44', name: 'Puerta metalica de carga', type: 'wall', x: 38, y: 10, width: 1, height: 4, category: 'door' },
      { id: '45', name: 'Ventana alta pequeña con barrotes', type: 'wall', x: 32, y: 0.2, width: 2.5, height: 0.8, category: 'structure' },
      { id: '46', name: 'Columna hormigon sucios 1', type: 'wall', x: 4, y: 5, width: 2, height: 2, category: 'structure' },
      { id: '47', name: 'Caja carton vacia 1', type: 'floor', x: 9, y: 3, width: 1.5, height: 1.5, category: 'cover' },
      { id: '48', name: 'Caja carton vacia 2', type: 'floor', x: 3, y: 8, width: 1.5, height: 1.5, category: 'cover' },
      { id: '49', name: 'Caja carton vacia 3', type: 'floor', x: 10, y: 14, width: 1.5, height: 1.5, category: 'cover' },
      { id: '50', name: 'Pales madera apilados', type: 'floor', x: 13, y: 13, width: 3, height: 3, category: 'cover' },
      { id: '51', name: 'carretilla de mano', type: 'floor', x: 22, y: 10, width: 1.2, height: 1.8, category: 'obstacle' },
      { id: '52', name: 'transpaleta manual', type: 'floor', x: 25, y: 3, width: 1, height: 2.5, category: 'obstacle' },
      { id: '53', name: 'barriles / bidones', type: 'floor', x: 31, y: 3, width: 2.5, height: 2.5, category: 'cover' },
      { id: '54', name: 'Sacos harina', type: 'floor', x: 35, y: 5, width: 2, height: 2.5, category: 'cover' },
      { id: '55', name: 'Sacos azucar', type: 'floor', x: 34, y: 12, width: 2, height: 2.5, category: 'cover' },
      { id: '56', name: 'Monton de cajas', type: 'floor', x: 30, y: 15, width: 3.5, height: 3, category: 'cover' },
      { id: '57', name: 'Carros de almacen', type: 'floor', x: 23, y: 14, width: 2, height: 1.5, category: 'obstacle' },
      { id: '58', name: 'Charcos de liquido', type: 'structure', x: 12, y: 9, width: 3, height: 1.5, category: 'hazard' },
      { id: '59', name: 'Trozos pequeños de papel', type: 'structure', x: 17, y: 15, width: 2, height: 1, category: 'detail' },
      { id: '60', name: 'Suelo sucio 1', type: 'structure', x: 4, y: 3, width: 3, height: 2, category: 'floor_detail' },
      { id: '61', name: 'Suelo sucio 2', type: 'structure', x: 14, y: 10, width: 4, height: 3, category: 'floor_detail' },
      { id: '62', name: 'Suelo sucio 3', type: 'structure', x: 29, y: 10, width: 3, height: 2, category: 'floor_detail' },
      { id: '63', name: 'Pared sucia 1', type: 'structure', x: 1, y: 2, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '64', name: 'Pared sucia 2', type: 'structure', x: 19.5, y: 10, width: 0.5, height: 2.5, category: 'wall_detail' },
      { id: '65', name: 'Pared sucia 3', type: 'structure', x: 38, y: 5, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '66', name: 'Lampara industrial 1', type: 'structure', x: 5, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '67', name: 'Lampara industrial 2', type: 'structure', x: 25, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '68', name: 'Lampara industrial 3', type: 'structure', x: 13, y: 18.3, width: 1.5, height: 0.7, category: 'lighting' }
    ],
    enemies: [
      { x: 5, y: 6, type: 'ranged' },
      { x: 15, y: 12, type: 'melee' }
    ]
  },
  {
    id: 3,
    name: "Almacén en U - Zona de Carga",
    description: "Forma de U con patio central y múltiples accesos laterales",
    playerStart: { x: 2, y: 15 },
    exit: { x: 38, y: 15 },
    walls: [
      { x: 0, y: 0, width: 40, height: 1 },
      { x: 0, y: 0, width: 1, height: 30 },
      { x: 0, y: 29, width: 40, height: 1 },
      { x: 39, y: 0, width: 1, height: 30 },
      { x: 10, y: 8, width: 20, height: 1 },
      { x: 10, y: 8, width: 1, height: 7 },
      { x: 29, y: 8, width: 1, height: 7 },
      { x: 10, y: 21, width: 20, height: 1 },
      { x: 10, y: 14, width: 1, height: 8 },
      { x: 29, y: 14, width: 1, height: 8 }
    ],
    objects: [
      { id: '69', name: 'Estanteria alta con comida 1', type: 'wall', x: 2, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '70', name: 'Estanteria alta con comida 2', type: 'wall', x: 17, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '71', name: 'Estanteria alta con comida 3', type: 'wall', x: 32, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '72', name: 'Estanteria metalica vacia', type: 'wall', x: 2, y: 25, width: 4, height: 1.5, category: 'furniture' },
      { id: '73', name: 'Palés apoyados a la pared', type: 'wall', x: 1, y: 10, width: 2, height: 1.5, category: 'furniture' },
      { id: '74', name: 'Tuberias vistas en la pared', type: 'wall', x: 1, y: 17, width: 0.8, height: 8, category: 'structure' },
      { id: '75', name: 'Cuadros Electricos', type: 'wall', x: 38, y: 5, width: 0.8, height: 2.5, category: 'structure' },
      { id: '76', name: 'Extintor con Soporte', type: 'wall', x: 38, y: 23, width: 0.8, height: 1.2, category: 'prop' },
      { id: '77', name: 'Señales de seguridad', type: 'wall', x: 10, y: 1, width: 1.2, height: 0.8, category: 'prop' },
      { id: '78', name: 'Puerta metalica de carga', type: 'wall', x: 38, y: 13, width: 1, height: 4, category: 'door' },
      { id: '79', name: 'Ventana alta pequeña con barrotes', type: 'wall', x: 25, y: 0.2, width: 2.5, height: 0.8, category: 'structure' },
      { id: '80', name: 'Columna hormigon sucios 1', type: 'wall', x: 14, y: 12, width: 2.5, height: 2.5, category: 'structure' },
      { id: '81', name: 'Columna hormigon sucios 2', type: 'wall', x: 23, y: 12, width: 2.5, height: 2.5, category: 'structure' },
      { id: '82', name: 'Caja carton vacia 1', type: 'floor', x: 4, y: 4, width: 1.5, height: 1.5, category: 'cover' },
      { id: '83', name: 'Caja carton vacia 2', type: 'floor', x: 6, y: 5, width: 1.5, height: 1.5, category: 'cover' },
      { id: '84', name: 'Caja carton vacia 3', type: 'floor', x: 33, y: 5, width: 1.5, height: 1.5, category: 'cover' },
      { id: '85', name: 'Pales madera apilados', type: 'floor', x: 18, y: 10, width: 3, height: 3, category: 'cover' },
      { id: '86', name: 'carretilla de mano', type: 'floor', x: 11, y: 16, width: 1.2, height: 1.8, category: 'obstacle' },
      { id: '87', name: 'transpaleta manual', type: 'floor', x: 27, y: 16, width: 1, height: 2.5, category: 'obstacle' },
      { id: '88', name: 'barriles / bidones', type: 'floor', x: 4, y: 11, width: 2.5, height: 2.5, category: 'cover' },
      { id: '89', name: 'Sacos harina', type: 'floor', x: 3, y: 18, width: 2, height: 2.5, category: 'cover' },
      { id: '90', name: 'Sacos azucar', type: 'floor', x: 6, y: 18, width: 2, height: 2.5, category: 'cover' },
      { id: '91', name: 'Monton de cajas', type: 'floor', x: 32, y: 10, width: 3.5, height: 3, category: 'cover' },
      { id: '92', name: 'Carros de almacen', type: 'floor', x: 13, y: 23, width: 2, height: 1.5, category: 'obstacle' },
      { id: '93', name: 'Charcos de liquido', type: 'structure', x: 17, y: 16, width: 3, height: 1.5, category: 'hazard' },
      { id: '94', name: 'Trozos pequeños de papel', type: 'structure', x: 24, y: 25, width: 2, height: 1, category: 'detail' },
      { id: '95', name: 'Suelo sucio 1', type: 'structure', x: 12, y: 10, width: 4, height: 3, category: 'floor_detail' },
      { id: '96', name: 'Suelo sucio 2', type: 'structure', x: 31, y: 20, width: 5, height: 4, category: 'floor_detail' },
      { id: '97', name: 'Suelo sucio 3', type: 'structure', x: 4, y: 23, width: 3, height: 2, category: 'floor_detail' },
      { id: '98', name: 'Pared sucia 1', type: 'structure', x: 1, y: 4, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '99', name: 'Pared sucia 2', type: 'structure', x: 10.5, y: 9, width: 0.5, height: 5, category: 'wall_detail' },
      { id: '100', name: 'Pared sucia 3', type: 'structure', x: 29.5, y: 15, width: 0.5, height: 6, category: 'wall_detail' },
      { id: '101', name: 'Lampara industrial 1', type: 'structure', x: 8, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '102', name: 'Lampara industrial 2', type: 'structure', x: 20, y: 11, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '103', name: 'Lampara industrial 3', type: 'structure', x: 28, y: 25, width: 1.5, height: 0.7, category: 'lighting' }
    ],
    enemies: [
      { x: 8, y: 6, type: 'ranged' },
      { x: 32, y: 24, type: 'melee' },
      { x: 20, y: 18, type: 'ranged' }
    ]
  },
  {
    id: 4,
    name: "Laberinto del Almacén",
    description: "Múltiples pasillos estrechos que se cruzan con esquinas cerradas",
    playerStart: { x: 2, y: 2 },
    exit: { x: 37, y: 27 },
    walls: [
      { x: 0, y: 0, width: 40, height: 1 },
      { x: 0, y: 0, width: 1, height: 30 },
      { x: 0, y: 29, width: 40, height: 1 },
      { x: 39, y: 0, width: 1, height: 30 },
      { x: 10, y: 2, width: 1, height: 10 },
      { x: 10, y: 16, width: 1, height: 12 },
      { x: 20, y: 2, width: 1, height: 12 },
      { x: 20, y: 18, width: 1, height: 10 },
      { x: 30, y: 4, width: 1, height: 10 },
      { x: 30, y: 18, width: 1, height: 10 },
      { x: 4, y: 8, width: 6, height: 1 },
      { x: 14, y: 22, width: 6, height: 1 },
      { x: 24, y: 8, width: 6, height: 1 },
      { x: 24, y: 24, width: 6, height: 1 }
    ],
    objects: [
      { id: '104', name: 'Estanteria alta con comida 1', type: 'wall', x: 2, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '105', name: 'Estanteria alta con comida 2', type: 'wall', x: 17, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '106', name: 'Estanteria alta con comida 3', type: 'wall', x: 33, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '107', name: 'Estanteria metalica vacia', type: 'wall', x: 9, y: 22, width: 4, height: 1.5, category: 'furniture' },
      { id: '108', name: 'Palés apoyados a la pared', type: 'wall', x: 1, y: 6, width: 2, height: 1.5, category: 'furniture' },
      { id: '109', name: 'Tuberias vistas en la pared', type: 'wall', x: 8.2, y: 7, width: 0.8, height: 6, category: 'structure' },
      { id: '110', name: 'Cuadros Electricos', type: 'wall', x: 16.2, y: 10, width: 0.8, height: 2.5, category: 'structure' },
      { id: '111', name: 'Extintor con Soporte', type: 'wall', x: 24.2, y: 5, width: 0.8, height: 1.2, category: 'prop' },
      { id: '112', name: 'Señales de seguridad', type: 'wall', x: 32.2, y: 8, width: 0.8, height: 1, category: 'prop' },
      { id: '113', name: 'Puerta metalica de carga', type: 'wall', x: 38, y: 24, width: 1, height: 4, category: 'door' },
      { id: '114', name: 'Ventana alta pequeña con barrotes', type: 'wall', x: 12, y: 0.2, width: 2.5, height: 0.8, category: 'structure' },
      { id: '115', name: 'Columna hormigon sucios 1', type: 'wall', x: 5, y: 15, width: 2, height: 2, category: 'structure' },
      { id: '116', name: 'Columna hormigon sucios 2', type: 'wall', x: 20, y: 10, width: 2, height: 2, category: 'structure' },
      { id: '117', name: 'Caja carton vacia 1', type: 'floor', x: 3, y: 4, width: 1.5, height: 1.5, category: 'cover' },
      { id: '118', name: 'Caja carton vacia 2', type: 'floor', x: 10, y: 6, width: 1.5, height: 1.5, category: 'cover' },
      { id: '119', name: 'Caja carton vacia 3', type: 'floor', x: 18, y: 5, width: 1.5, height: 1.5, category: 'cover' },
      { id: '120', name: 'Pales madera apilados', type: 'floor', x: 26, y: 8, width: 3, height: 3, category: 'cover' },
      { id: '121', name: 'carretilla de mano', type: 'floor', x: 34, y: 10, width: 1.2, height: 1.8, category: 'obstacle' },
      { id: '122', name: 'transpaleta manual', type: 'floor', x: 11, y: 16, width: 1, height: 2.5, category: 'obstacle' },
      { id: '123', name: 'barriles / bidones', type: 'floor', x: 4, y: 20, width: 2.5, height: 2.5, category: 'cover' },
      { id: '124', name: 'Sacos harina', type: 'floor', x: 13, y: 20, width: 2, height: 2.5, category: 'cover' },
      { id: '125', name: 'Sacos azucar', type: 'floor', x: 22, y: 21, width: 2, height: 2.5, category: 'cover' },
      { id: '126', name: 'Monton de cajas', type: 'floor', x: 28, y: 20, width: 3.5, height: 3, category: 'cover' },
      { id: '127', name: 'Carros de almacen', type: 'floor', x: 35, y: 18, width: 2, height: 1.5, category: 'obstacle' },
      { id: '128', name: 'Charcos de liquido', type: 'structure', x: 6, y: 12, width: 2, height: 1.5, category: 'hazard' },
      { id: '129', name: 'Trozos pequeños de papel', type: 'structure', x: 30, y: 15, width: 2, height: 1, category: 'detail' },
      { id: '130', name: 'Suelo sucio 1', type: 'structure', x: 10, y: 10, width: 4, height: 3, category: 'floor_detail' },
      { id: '131', name: 'Suelo sucio 2', type: 'structure', x: 25, y: 14, width: 5, height: 3, category: 'floor_detail' },
      { id: '132', name: 'Suelo sucio 3', type: 'structure', x: 17, y: 24, width: 4, height: 3, category: 'floor_detail' },
      { id: '133', name: 'Pared sucia 1', type: 'structure', x: 1, y: 15, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '134', name: 'Pared sucia 2', type: 'structure', x: 16.5, y: 12, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '135', name: 'Pared sucia 3', type: 'structure', x: 38, y: 10, width: 0.5, height: 5, category: 'wall_detail' },
      { id: '136', name: 'Lampara industrial 1', type: 'structure', x: 6, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '137', name: 'Lampara industrial 2', type: 'structure', x: 19, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '138', name: 'Lampara industrial 3', type: 'structure', x: 27, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' }
    ],
    enemies: [
      { x: 6, y: 8, type: 'melee' },
      { x: 14, y: 12, type: 'ranged' },
      { x: 26, y: 16, type: 'melee' },
      { x: 34, y: 14, type: 'ranged' }
    ]
  },
  {
    id: 5,
    name: "Almacén Fragmentado",
    description: "Múltiples salas pequeñas conectadas con pasillos estrechos",
    playerStart: { x: 2, y: 2 },
    exit: { x: 37, y: 27 },
    walls: [
      { x: 0, y: 0, width: 40, height: 1 },
      { x: 0, y: 0, width: 1, height: 30 },
      { x: 0, y: 29, width: 40, height: 1 },
      { x: 39, y: 0, width: 1, height: 30 },
      { x: 12, y: 1, width: 1, height: 10 },
      { x: 25, y: 1, width: 1, height: 12 },
      { x: 6, y: 14, width: 1, height: 10 },
      { x: 18, y: 16, width: 1, height: 13 },
      { x: 32, y: 15, width: 1, height: 10 },
      { x: 1, y: 8, width: 8, height: 1 },
      { x: 13, y: 6, width: 7, height: 1 },
      { x: 26, y: 9, width: 8, height: 1 },
      { x: 1, y: 20, width: 6, height: 1 },
      { x: 12, y: 23, width: 7, height: 1 },
      { x: 25, y: 21, width: 8, height: 1 }
    ],
    objects: [
      { id: '139', name: 'Estanteria alta con comida 1', type: 'wall', x: 2, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '140', name: 'Estanteria alta con comida 2', type: 'wall', x: 14, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '141', name: 'Estanteria alta con comida 3', type: 'wall', x: 27, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '142', name: 'Estanteria metalica vacia', type: 'wall', x: 2, y: 25, width: 4, height: 1.5, category: 'furniture' },
      { id: '143', name: 'Palés apoyados a la pared', type: 'wall', x: 1, y: 10, width: 2, height: 1.5, category: 'furniture' },
      { id: '144', name: 'Tuberias vistas en la pared', type: 'wall', x: 12.2, y: 3, width: 0.8, height: 7, category: 'structure' },
      { id: '145', name: 'Cuadros Electricos', type: 'wall', x: 25.2, y: 4, width: 0.8, height: 2.5, category: 'structure' },
      { id: '146', name: 'Extintor con Soporte', type: 'wall', x: 6.2, y: 16, width: 0.8, height: 1.2, category: 'prop' },
      { id: '147', name: 'Señales de seguridad', type: 'wall', x: 18.2, y: 18, width: 0.8, height: 1, category: 'prop' },
      { id: '148', name: 'Puerta metalica de carga', type: 'wall', x: 38, y: 8, width: 1, height: 4, category: 'door' },
      { id: '149', name: 'Ventana alta pequeña con barrotes', type: 'wall', x: 8, y: 0.2, width: 2.5, height: 0.8, category: 'structure' },
      { id: '150', name: 'Columna hormigon sucios 1', type: 'wall', x: 8, y: 4, width: 2, height: 2, category: 'structure' },
      { id: '151', name: 'Columna hormigon sucios 2', type: 'wall', x: 20, y: 5, width: 2, height: 2, category: 'structure' },
      { id: '152', name: 'Columna hormigon sucios 3', type: 'wall', x: 35, y: 6, width: 2, height: 2, category: 'structure' },
      { id: '153', name: 'Caja carton vacia 1', type: 'floor', x: 3, y: 3, width: 1.5, height: 1.5, category: 'cover' },
      { id: '154', name: 'Caja carton vacia 2', type: 'floor', x: 15, y: 4, width: 1.5, height: 1.5, category: 'cover' },
      { id: '155', name: 'Caja carton vacia 3', type: 'floor', x: 28, y: 5, width: 1.5, height: 1.5, category: 'cover' },
      { id: '156', name: 'Pales madera apilados', type: 'floor', x: 9, y: 10, width: 2.5, height: 2.5, category: 'cover' },
      { id: '157', name: 'carretilla de mano', type: 'floor', x: 22, y: 11, width: 1.2, height: 1.8, category: 'obstacle' },
      { id: '158', name: 'transpaleta manual', type: 'floor', x: 34, y: 11, width: 1, height: 2.5, category: 'obstacle' },
      { id: '159', name: 'barriles / bidones', type: 'floor', x: 3, y: 16, width: 2.5, height: 2.5, category: 'cover' },
      { id: '160', name: 'Sacos harina', type: 'floor', x: 9, y: 19, width: 2, height: 2.5, category: 'cover' },
      { id: '161', name: 'Sacos azucar', type: 'floor', x: 13, y: 18, width: 2, height: 2.5, category: 'cover' },
      { id: '162', name: 'Monton de cajas', type: 'floor', x: 22, y: 19, width: 3.5, height: 3, category: 'cover' },
      { id: '163', name: 'Carros de almacen', type: 'floor', x: 28, y: 17, width: 2, height: 1.5, category: 'obstacle' },
      { id: '164', name: 'Charcos de liquido', type: 'structure', x: 10, y: 15, width: 3, height: 1.5, category: 'hazard' },
      { id: '165', name: 'Trozos pequeños de papel', type: 'structure', x: 35, y: 19, width: 2, height: 1, category: 'detail' },
      { id: '166', name: 'Suelo sucio 1', type: 'structure', x: 4, y: 11, width: 4, height: 2, category: 'floor_detail' },
      { id: '167', name: 'Suelo sucio 2', type: 'structure', x: 17, y: 8, width: 5, height: 3, category: 'floor_detail' },
      { id: '168', name: 'Suelo sucio 3', type: 'structure', x: 28, y: 23, width: 4, height: 3, category: 'floor_detail' },
      { id: '169', name: 'Pared sucia 1', type: 'structure', x: 1, y: 4, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '170', name: 'Pared sucia 2', type: 'structure', x: 18.5, y: 20, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '171', name: 'Pared sucia 3', type: 'structure', x: 32.5, y: 17, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '172', name: 'Lampara industrial 1', type: 'structure', x: 5, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '173', name: 'Lampara industrial 2', type: 'structure', x: 20, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '174', name: 'Lampara industrial 3', type: 'structure', x: 15, y: 25, width: 1.5, height: 0.7, category: 'lighting' }
    ],
    enemies: [
      { x: 5, y: 5, type: 'ranged' },
      { x: 17, y: 8, type: 'melee' },
      { x: 30, y: 7, type: 'ranged' },
      { x: 8, y: 22, type: 'melee' },
      { x: 25, y: 24, type: 'ranged' }
    ]
  },
  {
    id: 6,
    name: "Espiral del Almacén",
    description: "Diseño en espiral que gira hacia el centro",
    playerStart: { x: 2, y: 2 },
    exit: { x: 20, y: 15 },
    walls: [
      { x: 0, y: 0, width: 40, height: 1 },
      { x: 0, y: 0, width: 1, height: 30 },
      { x: 0, y: 29, width: 40, height: 1 },
      { x: 39, y: 0, width: 1, height: 30 },
      { x: 4, y: 4, width: 32, height: 1 },
      { x: 35, y: 4, width: 1, height: 21 },
      { x: 8, y: 24, width: 28, height: 1 },
      { x: 8, y: 8, width: 1, height: 17 },
      { x: 8, y: 8, width: 24, height: 1 },
      { x: 31, y: 8, width: 1, height: 13 },
      { x: 12, y: 20, width: 20, height: 1 },
      { x: 12, y: 12, width: 1, height: 9 },
      { x: 12, y: 12, width: 16, height: 1 },
      { x: 27, y: 12, width: 1, height: 5 }
    ],
    objects: [
      { id: '175', name: 'Estanteria alta con comida 1', type: 'wall', x: 2, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '176', name: 'Estanteria alta con comida 2', type: 'wall', x: 16, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '177', name: 'Estanteria alta con comida 3', type: 'wall', x: 30, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '178', name: 'Estanteria metalica vacia', type: 'wall', x: 9, y: 25, width: 4, height: 1.5, category: 'furniture' },
      { id: '179', name: 'Palés apoyados a la pared', type: 'wall', x: 1, y: 6, width: 2, height: 1.5, category: 'furniture' },
      { id: '180', name: 'Tuberias vistas en la pared', type: 'wall', x: 1, y: 15, width: 0.8, height: 8, category: 'structure' },
      { id: '181', name: 'Cuadros Electricos', type: 'wall', x: 38, y: 10, width: 0.8, height: 2.5, category: 'structure' },
      { id: '182', name: 'Extintor con Soporte', type: 'wall', x: 8.2, y: 10, width: 0.8, height: 1.2, category: 'prop' },
      { id: '183', name: 'Señales de seguridad', type: 'wall', x: 12.2, y: 14, width: 0.8, height: 1, category: 'prop' },
      { id: '184', name: 'Puerta metalica de carga', type: 'wall', x: 38, y: 20, width: 1, height: 4, category: 'door' },
      { id: '185', name: 'Ventana alta pequeña con barrotes', type: 'wall', x: 10, y: 0.2, width: 2.5, height: 0.8, category: 'structure' },
      { id: '186', name: 'Columna hormigon sucios 1', type: 'wall', x: 10, y: 5, width: 2, height: 2, category: 'structure' },
      { id: '187', name: 'Columna hormigon sucios 2', type: 'wall', x: 25, y: 5, width: 2, height: 2, category: 'structure' },
      { id: '188', name: 'Columna hormigon sucios 3', type: 'wall', x: 16, y: 14, width: 2.5, height: 2.5, category: 'structure' },
      { id: '189', name: 'Caja carton vacia 1', type: 'floor', x: 5, y: 6, width: 1.5, height: 1.5, category: 'cover' },
      { id: '190', name: 'Caja carton vacia 2', type: 'floor', x: 13, y: 5, width: 1.5, height: 1.5, category: 'cover' },
      { id: '191', name: 'Caja carton vacia 3', type: 'floor', x: 29, y: 6, width: 1.5, height: 1.5, category: 'cover' },
      { id: '192', name: 'Pales madera apilados', type: 'floor', x: 20, y: 5, width: 3, height: 3, category: 'cover' },
      { id: '193', name: 'carretilla de mano', type: 'floor', x: 33, y: 10, width: 1.2, height: 1.8, category: 'obstacle' },
      { id: '194', name: 'transpaleta manual', type: 'floor', x: 10, y: 18, width: 1, height: 2.5, category: 'obstacle' },
      { id: '195', name: 'barriles / bidones', type: 'floor', x: 28, y: 10, width: 2.5, height: 2.5, category: 'cover' },
      { id: '196', name: 'Sacos harina', type: 'floor', x: 14, y: 9, width: 2, height: 2.5, category: 'cover' },
      { id: '197', name: 'Sacos azucar', type: 'floor', x: 22, y: 10, width: 2, height: 2.5, category: 'cover' },
      { id: '198', name: 'Monton de cajas', type: 'floor', x: 18, y: 21, width: 3.5, height: 3, category: 'cover' },
      { id: '199', name: 'Carros de almacen', type: 'floor', x: 13, y: 22, width: 2, height: 1.5, category: 'obstacle' },
      { id: '200', name: 'Charcos de liquido', type: 'structure', x: 24, y: 17, width: 3, height: 1.5, category: 'hazard' },
      { id: '201', name: 'Trozos pequeños de papel', type: 'structure', x: 29, y: 22, width: 2, height: 1, category: 'detail' },
      { id: '202', name: 'Suelo sucio 1', type: 'structure', x: 6, y: 10, width: 2, height: 3, category: 'floor_detail' },
      { id: '203', name: 'Suelo sucio 2', type: 'structure', x: 24, y: 13, width: 4, height: 3, category: 'floor_detail' },
      { id: '204', name: 'Suelo sucio 3', type: 'structure', x: 15, y: 25, width: 5, height: 2, category: 'floor_detail' },
      { id: '205', name: 'Pared sucia 1', type: 'structure', x: 4.5, y: 5, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '206', name: 'Pared sucia 2', type: 'structure', x: 35.5, y: 12, width: 0.5, height: 5, category: 'wall_detail' },
      { id: '207', name: 'Pared sucia 3', type: 'structure', x: 12.5, y: 15, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '208', name: 'Lampara industrial 1', type: 'structure', x: 7, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '209', name: 'Lampara industrial 2', type: 'structure', x: 25, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '210', name: 'Lampara industrial 3', type: 'structure', x: 20, y: 17, width: 1.5, height: 0.7, category: 'lighting' }
    ],
    enemies: [
      { x: 7, y: 6, type: 'ranged' },
      { x: 32, y: 7, type: 'melee' },
      { x: 15, y: 11, type: 'ranged' },
      { x: 25, y: 15, type: 'melee' },
      { x: 12, y: 19, type: 'ranged' }
    ]
  },
  {
    id: 7,
    name: "Almacén en Cruz",
    description: "Diseño en forma de cruz con pasillo central y brazos laterales",
    playerStart: { x: 2, y: 14 },
    exit: { x: 37, y: 14 },
    walls: [
      { x: 0, y: 0, width: 40, height: 1 },
      { x: 0, y: 0, width: 1, height: 30 },
      { x: 0, y: 29, width: 40, height: 1 },
      { x: 39, y: 0, width: 1, height: 30 },
      { x: 14, y: 1, width: 1, height: 8 },
      { x: 25, y: 1, width: 1, height: 8 },
      { x: 14, y: 20, width: 1, height: 9 },
      { x: 25, y: 20, width: 1, height: 9 },
      { x: 1, y: 8, width: 14, height: 1 },
      { x: 1, y: 19, width: 14, height: 1 },
      { x: 25, y: 8, width: 14, height: 1 },
      { x: 25, y: 19, width: 14, height: 1 }
    ],
    objects: [
      { id: '211', name: 'Estanteria alta con comida 1', type: 'wall', x: 2, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '212', name: 'Estanteria alta con comida 2', type: 'wall', x: 16, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '213', name: 'Estanteria alta con comida 3', type: 'wall', x: 27, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '214', name: 'Estanteria metalica vacia', type: 'wall', x: 2, y: 25, width: 5, height: 1.5, category: 'furniture' },
      { id: '215', name: 'Palés apoyados a la pared', type: 'wall', x: 1, y: 12, width: 2, height: 1.5, category: 'furniture' },
      { id: '216', name: 'Tuberias vistas en la pared', type: 'wall', x: 14.2, y: 2, width: 0.8, height: 6, category: 'structure' },
      { id: '217', name: 'Cuadros Electicos', type: 'wall', x: 25.2, y: 2, width: 0.8, height: 2.5, category: 'structure' },
      { id: '218', name: 'Extintor con Soporte', type: 'wall', x: 14.2, y: 22, width: 0.8, height: 1.2, category: 'prop' },
      { id: '219', name: 'Señales de seguridad', type: 'wall', x: 25.2, y: 23, width: 0.8, height: 1, category: 'prop' },
      { id: '220', name: 'Puerta metalica de carga', type: 'wall', x: 38, y: 13, width: 1, height: 4, category: 'door' },
      { id: '221', name: 'Ventana alta pequeña con barrotes', type: 'wall', x: 10, y: 0.2, width: 2.5, height: 0.8, category: 'structure' },
      { id: '222', name: 'Columna hormigon sucios 1', type: 'wall', x: 17, y: 12, width: 2.5, height: 2.5, category: 'structure' },
      { id: '223', name: 'Columna hormigon sucios 2', type: 'wall', x: 21, y: 12, width: 2.5, height: 2.5, category: 'structure' },
      { id: '224', name: 'Caja carton vacia 1', type: 'floor', x: 4, y: 3, width: 1.5, height: 1.5, category: 'cover' },
      { id: '225', name: 'Caja carton vacia 2', type: 'floor', x: 18, y: 4, width: 1.5, height: 1.5, category: 'cover' },
      { id: '226', name: 'Caja carton vacia 3', type: 'floor', x: 30, y: 3, width: 1.5, height: 1.5, category: 'cover' },
      { id: '227', name: 'Pales madera apilados', type: 'floor', x: 5, y: 10, width: 3, height: 3, category: 'cover' },
      { id: '228', name: 'carretilla de mano', type: 'floor', x: 10, y: 11, width: 1.2, height: 1.8, category: 'obstacle' },
      { id: '229', name: 'transpaleta manual', type: 'floor', x: 28, y: 11, width: 1, height: 2.5, category: 'obstacle' },
      { id: '230', name: 'barriles / bidones', type: 'floor', x: 32, y: 10, width: 2.5, height: 2.5, category: 'cover' },
      { id: '231', name: 'Sacos harina', type: 'floor', x: 16, y: 9, width: 2, height: 2, category: 'cover' },
      { id: '232', name: 'Sacos azucar', type: 'floor', x: 22, y: 9, width: 2, height: 2, category: 'cover' },
      { id: '233', name: 'Monton de cajas', type: 'floor', x: 4, y: 21, width: 3.5, height: 3, category: 'cover' },
      { id: '234', name: 'Carros de almacen', type: 'floor', x: 10, y: 22, width: 2, height: 1.5, category: 'obstacle' },
      { id: '235', name: 'Charcos de liquido', type: 'structure', x: 16, y: 18, width: 3, height: 1.5, category: 'hazard' },
      { id: '236', name: 'Trozos pequeños de papel', type: 'structure', x: 29, y: 21, width: 2, height: 1, category: 'detail' },
      { id: '237', name: 'Suelo sucio 1', type: 'structure', x: 6, y: 5, width: 4, height: 2, category: 'floor_detail' },
      { id: '238', name: 'Suelo sucio 2', type: 'structure', x: 28, y: 5, width: 5, height: 3, category: 'floor_detail' },
      { id: '239', name: 'Suelo sucio 3', type: 'structure', x: 8, y: 23, width: 4, height: 3, category: 'floor_detail' },
      { id: '240', name: 'Pared sucia 1', type: 'structure', x: 1, y: 10, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '241', name: 'Pared sucia 2', type: 'structure', x: 14.5, y: 10, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '242', name: 'Pared sucia 3', type: 'structure', x: 38, y: 8, width: 0.5, height: 5, category: 'wall_detail' },
      { id: '243', name: 'Lampara industrial 1', type: 'structure', x: 8, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '244', name: 'Lampara industrial 2', type: 'structure', x: 20, y: 13, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '245', name: 'Lampara industrial 3', type: 'structure', x: 18, y: 25, width: 1.5, height: 0.7, category: 'lighting' }
    ],
    enemies: [
      { x: 6, y: 5, type: 'ranged' },
      { x: 33, y: 5, type: 'melee' },
      { x: 20, y: 11, type: 'ranged' },
      { x: 6, y: 24, type: 'melee' },
      { x: 32, y: 24, type: 'ranged' }
    ]
  },
  {
    id: 8,
    name: "Depósito Estrellado",
    description: "Diseño radial con múltiples salidas y esquinas",
    playerStart: { x: 20, y: 15 },
    exit: { x: 35, y: 5 },
    walls: [
      { x: 0, y: 0, width: 40, height: 1 },
      { x: 0, y: 0, width: 1, height: 30 },
      { x: 0, y: 29, width: 40, height: 1 },
      { x: 39, y: 0, width: 1, height: 30 },
      { x: 18, y: 1, width: 4, height: 8 },
      { x: 8, y: 8, width: 10, height: 1 },
      { x: 8, y: 8, width: 1, height: 6 },
      { x: 22, y: 8, width: 10, height: 1 },
      { x: 31, y: 8, width: 1, height: 6 },
      { x: 18, y: 21, width: 4, height: 8 },
      { x: 8, y: 20, width: 10, height: 1 },
      { x: 8, y: 14, width: 1, height: 7 },
      { x: 22, y: 20, width: 10, height: 1 },
      { x: 31, y: 14, width: 1, height: 7 }
    ],
    objects: [
      { id: '246', name: 'Estanteria alta con comida 1', type: 'wall', x: 2, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '247', name: 'Estanteria alta con comida 2', type: 'wall', x: 33, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '248', name: 'Estanteria alta con comida 3', type: 'wall', x: 9, y: 9, width: 4, height: 1.5, category: 'furniture' },
      { id: '249', name: 'Estanteria metalica vacia', type: 'wall', x: 26, y: 9, width: 4, height: 1.5, category: 'furniture' },
      { id: '250', name: 'Palés apoyados a la pared', type: 'wall', x: 1, y: 5, width: 2, height: 1.5, category: 'furniture' },
      { id: '251', name: 'Tuberias vistas en la pared', type: 'wall', x: 1, y: 18, width: 0.8, height: 7, category: 'structure' },
      { id: '252', name: 'Cuadros Electicos', type: 'wall', x: 38, y: 10, width: 0.8, height: 2.5, category: 'structure' },
      { id: '253', name: 'Extintor con Soporte', type: 'wall', x: 38, y: 20, width: 0.8, height: 1.2, category: 'prop' },
      { id: '254', name: 'Señales de seguridad', type: 'wall', x: 19, y: 1, width: 1.2, height: 0.8, category: 'prop' },
      { id: '255', name: 'Puerta metalica de carga', type: 'wall', x: 38, y: 3, width: 1, height: 4, category: 'door' },
      { id: '256', name: 'Ventana alta pequeña con barrotes', type: 'wall', x: 10, y: 0.2, width: 2.5, height: 0.8, category: 'structure' },
      { id: '257', name: 'Columna hormigon sucios 1', type: 'wall', x: 17, y: 13, width: 2.5, height: 2.5, category: 'structure' },
      { id: '258', name: 'Columna hormigon sucios 2', type: 'wall', x: 21, y: 13, width: 2.5, height: 2.5, category: 'structure' },
      { id: '259', name: 'Caja carton vacia 1', type: 'floor', x: 4, y: 4, width: 1.5, height: 1.5, category: 'cover' },
      { id: '260', name: 'Caja carton vacia 2', type: 'floor', x: 34, y: 4, width: 1.5, height: 1.5, category: 'cover' },
      { id: '261', name: 'Caja carton vacia 3', type: 'floor', x: 11, y: 12, width: 1.5, height: 1.5, category: 'cover' },
      { id: '262', name: 'Pales madera apilados', type: 'floor', x: 27, y: 12, width: 3, height: 3, category: 'cover' },
      { id: '263', name: 'carretilla de mano', type: 'floor', x: 4, y: 16, width: 1.2, height: 1.8, category: 'obstacle' },
      { id: '264', name: 'transpaleta manual', type: 'floor', x: 34, y: 16, width: 1, height: 2.5, category: 'obstacle' },
      { id: '265', name: 'barriles / bidones', type: 'floor', x: 10, y: 22, width: 2.5, height: 2.5, category: 'cover' },
      { id: '266', name: 'Sacos harina', type: 'floor', x: 27, y: 22, width: 2, height: 2.5, category: 'cover' },
      { id: '267', name: 'Sacos azucar', type: 'floor', x: 16, y: 23, width: 2, height: 2.5, category: 'cover' },
      { id: '268', name: 'Monton de cajas', type: 'floor', x: 4, y: 10, width: 3.5, height: 3, category: 'cover' },
      { id: '269', name: 'Carros de almacen', type: 'floor', x: 33, y: 11, width: 2, height: 1.5, category: 'obstacle' },
      { id: '270', name: 'Charcos de liquido', type: 'structure', x: 13, y: 17, width: 3, height: 1.5, category: 'hazard' },
      { id: '271', name: 'Trozos pequeños de papel', type: 'structure', x: 24, y: 17, width: 2, height: 1, category: 'detail' },
      { id: '272', name: 'Suelo sucio 1', type: 'structure', x: 10, y: 5, width: 4, height: 2, category: 'floor_detail' },
      { id: '273', name: 'Suelo sucio 2', type: 'structure', x: 25, y: 5, width: 5, height: 3, category: 'floor_detail' },
      { id: '274', name: 'Suelo sucio 3', type: 'structure', x: 19, y: 25, width: 3, height: 2, category: 'floor_detail' },
      { id: '275', name: 'Pared sucia 1', type: 'structure', x: 18.5, y: 3, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '276', name: 'Pared sucia 2', type: 'structure', x: 8.5, y: 10, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '277', name: 'Pared sucia 3', type: 'structure', x: 31.5, y: 15, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '278', name: 'Lampara industrial 1', type: 'structure', x: 15, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '279', name: 'Lampara industrial 2', type: 'structure', x: 13, y: 13, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '280', name: 'Lampara industrial 3', type: 'structure', x: 25, y: 13, width: 1.5, height: 0.7, category: 'lighting' }
    ],
    enemies: [
      { x: 6, y: 6, type: 'ranged' },
      { x: 34, y: 6, type: 'melee' },
      { x: 12, y: 15, type: 'ranged' },
      { x: 28, y: 15, type: 'melee' },
      { x: 20, y: 24, type: 'ranged' },
      { x: 15, y: 10, type: 'melee' }
    ]
  },
  {
    id: 9,
    name: "Almacén Hexagonal",
    description: "Estructura casi hexagonal con ángulos múltiples",
    playerStart: { x: 2, y: 15 },
    exit: { x: 37, y: 15 },
    walls: [
      { x: 0, y: 0, width: 40, height: 1 },
      { x: 0, y: 0, width: 1, height: 30 },
      { x: 0, y: 29, width: 40, height: 1 },
      { x: 39, y: 0, width: 1, height: 30 },
      { x: 10, y: 1, width: 1, height: 6 },
      { x: 10, y: 6, width: 10, height: 1 },
      { x: 19, y: 6, width: 1, height: 7 },
      { x: 19, y: 12, width: 10, height: 1 },
      { x: 28, y: 6, width: 1, height: 7 },
      { x: 28, y: 6, width: 7, height: 1 },
      { x: 34, y: 1, width: 1, height: 6 },
      { x: 10, y: 23, width: 1, height: 6 },
      { x: 10, y: 23, width: 10, height: 1 },
      { x: 19, y: 16, width: 1, height: 8 },
      { x: 19, y: 16, width: 10, height: 1 },
      { x: 28, y: 16, width: 1, height: 8 },
      { x: 28, y: 23, width: 7, height: 1 },
      { x: 34, y: 23, width: 1, height: 6 }
    ],
    objects: [
      { id: '281', name: 'Estanteria alta con comida 1', type: 'wall', x: 2, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '282', name: 'Estanteria alta con comida 2', type: 'wall', x: 20, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '283', name: 'Estanteria alta con comida 3', type: 'wall', x: 11, y: 7, width: 4, height: 1.5, category: 'furniture' },
      { id: '284', name: 'Estanteria metalica vacia', type: 'wall', x: 29, y: 7, width: 4, height: 1.5, category: 'furniture' },
      { id: '285', name: 'Palés apoyados a la pared', type: 'wall', x: 1, y: 12, width: 2, height: 1.5, category: 'furniture' },
      { id: '286', name: 'Tuberias vistas en la pared', type: 'wall', x: 10.2, y: 2, width: 0.8, height: 4, category: 'structure' },
      { id: '287', name: 'Cuadros Electicos', type: 'wall', x: 34.2, y: 2, width: 0.8, height: 2.5, category: 'structure' },
      { id: '288', name: 'Extintor con Soporte', type: 'wall', x: 19.2, y: 8, width: 0.8, height: 1.2, category: 'prop' },
      { id: '289', name: 'Señales de seguridad', type: 'wall', x: 28.2, y: 13, width: 0.8, height: 1, category: 'prop' },
      { id: '290', name: 'Puerta metalica de carga', type: 'wall', x: 38, y: 13, width: 1, height: 4, category: 'door' },
      { id: '291', name: 'Ventana alta pequeña con barrotes', type: 'wall', x: 12, y: 0.2, width: 2.5, height: 0.8, category: 'structure' },
      { id: '292', name: 'Columna hormigon sucios 1', type: 'wall', x: 5, y: 8, width: 2, height: 2, category: 'structure' },
      { id: '293', name: 'Columna hormigon sucios 2', type: 'wall', x: 22, y: 8, width: 2, height: 2, category: 'structure' },
      { id: '294', name: 'Columna hormigon sucios 3', type: 'wall', x: 33, y: 11, width: 2, height: 2, category: 'structure' },
      { id: '295', name: 'Caja carton vacia 1', type: 'floor', x: 4, y: 4, width: 1.5, height: 1.5, category: 'cover' },
      { id: '296', name: 'Caja carton vacia 2', type: 'floor', x: 16, y: 3, width: 1.5, height: 1.5, category: 'cover' },
      { id: '297', name: 'Caja carton vacia 3', type: 'floor', x: 30, y: 4, width: 1.5, height: 1.5, category: 'cover' },
      { id: '298', name: 'Pales madera apilados', type: 'floor', x: 13, y: 10, width: 3, height: 3, category: 'cover' },
      { id: '299', name: 'carretilla de mano', type: 'floor', x: 24, y: 10, width: 1.2, height: 1.8, category: 'obstacle' },
      { id: '300', name: 'transpaleta manual', type: 'floor', x: 22, y: 18, width: 1, height: 2.5, category: 'obstacle' },
      { id: '301', name: 'barriles / bidones', type: 'floor', x: 4, y: 18, width: 2.5, height: 2.5, category: 'cover' },
      { id: '302', name: 'Sacos harina', type: 'floor', x: 11, y: 18, width: 2, height: 2.5, category: 'cover' },
      { id: '303', name: 'Sacos azucar', type: 'floor', x: 15, y: 19, width: 2, height: 2.5, category: 'cover' },
      { id: '304', name: 'Monton de cajas', type: 'floor', x: 29, y: 18, width: 3.5, height: 3, category: 'cover' },
      { id: '305', name: 'Carros de almacen', type: 'floor', x: 6, y: 13, width: 2, height: 1.5, category: 'obstacle' },
      { id: '306', name: 'Charcos de liquido', type: 'structure', x: 23, y: 13, width: 3, height: 1.5, category: 'hazard' },
      { id: '307', name: 'Trozos pequeños de papel', type: 'structure', x: 35, y: 16, width: 2, height: 1, category: 'detail' },
      { id: '308', name: 'Suelo sucio 1', type: 'structure', x: 7, y: 5, width: 3, height: 2, category: 'floor_detail' },
      { id: '309', name: 'Suelo sucio 2', type: 'structure', x: 26, y: 9, width: 2, height: 3, category: 'floor_detail' },
      { id: '310', name: 'Suelo sucio 3', type: 'structure', x: 8, y: 21, width: 2, height: 2, category: 'floor_detail' },
      { id: '311', name: 'Pared sucia 1', type: 'structure', x: 1, y: 7, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '312', name: 'Pared sucia 2', type: 'structure', x: 19.5, y: 9, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '313', name: 'Pared sucia 3', type: 'structure', x: 34.5, y: 18, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '314', name: 'Lampara industrial 1', type: 'structure', x: 6, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '315', name: 'Lampara industrial 2', type: 'structure', x: 25, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '316', name: 'Lampara industrial 3', type: 'structure', x: 18, y: 20, width: 1.5, height: 0.7, category: 'lighting' }
    ],
    enemies: [
      { x: 6, y: 5, type: 'ranged' },
      { x: 25, y: 5, type: 'melee' },
      { x: 35, y: 8, type: 'ranged' },
      { x: 16, y: 13, type: 'melee' },
      { x: 8, y: 22, type: 'ranged' },
      { x: 26, y: 22, type: 'melee' }
    ]
  },
  {
    id: 10,
    name: "Depósito Ajedrezado",
    description: "Patrón de cuadrícula con múltiples habitaciones pequeñas",
    playerStart: { x: 2, y: 2 },
    exit: { x: 37, y: 27 },
    walls: [
      { x: 0, y: 0, width: 40, height: 1 },
      { x: 0, y: 0, width: 1, height: 30 },
      { x: 0, y: 29, width: 40, height: 1 },
      { x: 39, y: 0, width: 1, height: 30 },
      { x: 8, y: 2, width: 1, height: 6 },
      { x: 8, y: 10, width: 1, height: 10 },
      { x: 8, y: 22, width: 1, height: 6 },
      { x: 16, y: 2, width: 1, height: 6 },
      { x: 16, y: 10, width: 1, height: 10 },
      { x: 16, y: 22, width: 1, height: 6 },
      { x: 24, y: 2, width: 1, height: 6 },
      { x: 24, y: 10, width: 1, height: 10 },
      { x: 24, y: 22, width: 1, height: 6 },
      { x: 32, y: 2, width: 1, height: 6 },
      { x: 32, y: 10, width: 1, height: 10 },
      { x: 32, y: 22, width: 1, height: 6 }
    ],
    objects: [
      { id: '317', name: 'Estanteria alta con comida 1', type: 'wall', x: 2, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '318', name: 'Estanteria alta con comida 2', type: 'wall', x: 12, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '319', name: 'Estanteria alta con comida 3', type: 'wall', x: 22, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '320', name: 'Estanteria metalica vacia', type: 'wall', x: 32, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '321', name: 'Palés apoyados a la pared', type: 'wall', x: 1, y: 4, width: 2, height: 1.5, category: 'furniture' },
      { id: '322', name: 'Tuberias vistas en la pared', type: 'wall', x: 10.2, y: 2, width: 0.8, height: 6, category: 'structure' },
      { id: '323', name: 'Cuadros Electicos', type: 'wall', x: 20.2, y: 3, width: 0.8, height: 2.5, category: 'structure' },
      { id: '324', name: 'Extintor con Soporte', type: 'wall', x: 30.2, y: 4, width: 0.8, height: 1.2, category: 'prop' },
      { id: '325', name: 'Señales de seguridad', type: 'wall', x: 5.2, y: 16, width: 0.8, height: 1, category: 'prop' },
      { id: '326', name: 'Puerta metalica de carga', type: 'wall', x: 38, y: 5, width: 1, height: 4, category: 'door' },
      { id: '327', name: 'Ventana alta pequeña con barrotes', type: 'wall', x: 8, y: 0.2, width: 2, height: 0.8, category: 'structure' },
      { id: '328', name: 'Columna hormigon sucios 1', type: 'wall', x: 7, y: 11, width: 2, height: 2, category: 'structure' },
      { id: '329', name: 'Columna hormigon sucios 2', type: 'wall', x: 17, y: 11, width: 2, height: 2, category: 'structure' },
      { id: '330', name: 'Columna hormigon sucios 3', type: 'wall', x: 27, y: 11, width: 2, height: 2, category: 'structure' },
      { id: '331', name: 'Caja carton vacia 1', type: 'floor', x: 4, y: 3, width: 1.5, height: 1.5, category: 'cover' },
      { id: '332', name: 'Caja carton vacia 2', type: 'floor', x: 14, y: 3, width: 1.5, height: 1.5, category: 'cover' },
      { id: '333', name: 'Caja carton vacia 3', type: 'floor', x: 24, y: 4, width: 1.5, height: 1.5, category: 'cover' },
      { id: '334', name: 'Pales madera apilados', type: 'floor', x: 34, y: 4, width: 2.5, height: 2.5, category: 'cover' },
      { id: '335', name: 'carretilla de mano', type: 'floor', x: 3, y: 11, width: 1.2, height: 1.8, category: 'obstacle' },
      { id: '336', name: 'transpaleta manual', type: 'floor', x: 13, y: 11, width: 1, height: 2.5, category: 'obstacle' },
      { id: '337', name: 'barriles / bidones', type: 'floor', x: 23, y: 11, width: 2.5, height: 2.5, category: 'cover' },
      { id: '338', name: 'Sacos harina', type: 'floor', x: 33, y: 11, width: 2, height: 2.5, category: 'cover' },
      { id: '339', name: 'Sacos azucar', type: 'floor', x: 3, y: 16, width: 2, height: 2.5, category: 'cover' },
      { id: '340', name: 'Monton de cajas', type: 'floor', x: 11, y: 16, width: 3.5, height: 3, category: 'cover' },
      { id: '341', name: 'Carros de almacen', type: 'floor', x: 22, y: 16, width: 2, height: 1.5, category: 'obstacle' },
      { id: '342', name: 'Charcos de liquido', type: 'structure', x: 32, y: 16, width: 3, height: 1.5, category: 'hazard' },
      { id: '343', name: 'Trozos pequeños de papel', type: 'structure', x: 7, y: 21, width: 2, height: 1, category: 'detail' },
      { id: '344', name: 'Suelo sucio 1', type: 'structure', x: 2, y: 21, width: 4, height: 3, category: 'floor_detail' },
      { id: '345', name: 'Suelo sucio 2', type: 'structure', x: 16, y: 21, width: 3, height: 2, category: 'floor_detail' },
      { id: '346', name: 'Suelo sucio 3', type: 'structure', x: 27, y: 22, width: 4, height: 3, category: 'floor_detail' },
      { id: '347', name: 'Pared sucia 1', type: 'structure', x: 1, y: 11, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '348', name: 'Pared sucia 2', type: 'structure', x: 15.5, y: 15, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '349', name: 'Pared sucia 3', type: 'structure', x: 38, y: 20, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '350', name: 'Lampara industrial 1', type: 'structure', x: 5, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '351', name: 'Lampara industrial 2', type: 'structure', x: 18, y: 12, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '352', name: 'Lampara industrial 3', type: 'structure', x: 25, y: 22, width: 1.5, height: 0.7, category: 'lighting' }
    ],
    enemies: [
      { x: 6, y: 5, type: 'ranged' },
      { x: 16, y: 5, type: 'melee' },
      { x: 26, y: 6, type: 'ranged' },
      { x: 8, y: 12, type: 'melee' },
      { x: 28, y: 13, type: 'ranged' },
      { x: 4, y: 23, type: 'melee' },
      { x: 18, y: 23, type: 'ranged' }
    ]
  },
  {
    id: 11,
    name: "Corredor del Caos",
    description: "Pasillo serpenteante con múltiples recodos y giros cerrados",
    playerStart: { x: 2, y: 2 },
    exit: { x: 37, y: 27 },
    walls: [
      { x: 0, y: 0, width: 40, height: 1 },
      { x: 0, y: 0, width: 1, height: 30 },
      { x: 0, y: 29, width: 40, height: 1 },
      { x: 39, y: 0, width: 1, height: 30 },
      { x: 6, y: 4, width: 10, height: 6 },
      { x: 22, y: 6, width: 12, height: 6 },
      { x: 8, y: 18, width: 10, height: 7 },
      { x: 24, y: 18, width: 10, height: 7 },
      { x: 18, y: 10, width: 1, height: 4 },
      { x: 18, y: 16, width: 1, height: 4 }
    ],
    objects: [
      { id: '353', name: 'Estanteria alta con comida 1', type: 'wall', x: 2, y: 1, width: 4, height: 1.5, category: 'furniture' },
      { id: '354', name: 'Estanteria alta con comida 2', type: 'wall', x: 21, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '355', name: 'Estanteria alta con comida 3', type: 'wall', x: 9, y: 8, width: 4, height: 1.5, category: 'furniture' },
      { id: '356', name: 'Estanteria metalica vacia', type: 'wall', x: 14, y: 24, width: 5, height: 1.5, category: 'furniture' },
      { id: '357', name: 'Palés apoyados a la pared', type: 'wall', x: 1, y: 5, width: 2, height: 1.5, category: 'furniture' },
      { id: '358', name: 'Tuberias vistas en la pared', type: 'wall', x: 8.2, y: 2, width: 0.8, height: 5, category: 'structure' },
      { id: '359', name: 'Cuadros Electicos', type: 'wall', x: 19.2, y: 2, width: 0.8, height: 2, category: 'structure' },
      { id: '360', name: 'Extintor con Soporte', type: 'wall', x: 27.2, y: 5, width: 0.8, height: 1.2, category: 'prop' },
      { id: '361', name: 'Señales de seguridad', type: 'wall', x: 5.2, y: 14, width: 0.8, height: 1, category: 'prop' },
      { id: '362', name: 'Puerta metalica de carga', type: 'wall', x: 38, y: 24, width: 1, height: 4, category: 'door' },
      { id: '363', name: 'Ventana alta pequeña con barrotes', type: 'wall', x: 12, y: 0.2, width: 2.5, height: 0.8, category: 'structure' },
      { id: '364', name: 'Columna hormigon sucios 1', type: 'wall', x: 10, y: 4, width: 2, height: 2, category: 'structure' },
      { id: '365', name: 'Columna hormigon sucios 2', type: 'wall', x: 24, y: 6, width: 2, height: 2, category: 'structure' },
      { id: '366', name: 'Columna hormigon sucios 3', type: 'wall', x: 17, y: 13, width: 2, height: 2, category: 'structure' },
      { id: '367', name: 'Caja carton vacia 1', type: 'floor', x: 3, y: 3, width: 1.5, height: 1.5, category: 'cover' },
      { id: '368', name: 'Caja carton vacia 2', type: 'floor', x: 14, y: 2, width: 1.5, height: 1.5, category: 'cover' },
      { id: '369', name: 'Caja carton vacia 3', type: 'floor', x: 30, y: 6, width: 1.5, height: 1.5, category: 'cover' },
      { id: '370', name: 'Pales madera apilados', type: 'floor', x: 11, y: 9, width: 3, height: 3, category: 'cover' },
      { id: '371', name: 'carretilla de mano', type: 'floor', x: 7, y: 14, width: 1.2, height: 1.8, category: 'obstacle' },
      { id: '372', name: 'transpaleta manual', type: 'floor', x: 17, y: 9, width: 1, height: 2.5, category: 'obstacle' },
      { id: '373', name: 'barriles / bidones', type: 'floor', x: 23, y: 12, width: 2.5, height: 2.5, category: 'cover' },
      { id: '374', name: 'Sacos harina', type: 'floor', x: 32, y: 10, width: 2, height: 2.5, category: 'cover' },
      { id: '375', name: 'Sacos azucar', type: 'floor', x: 30, y: 17, width: 2, height: 2.5, category: 'cover' },
      { id: '376', name: 'Monton de cajas', type: 'floor', x: 8, y: 19, width: 3.5, height: 3, category: 'cover' },
      { id: '377', name: 'Carros de almacen', type: 'floor', x: 20, y: 19, width: 2, height: 1.5, category: 'obstacle' },
      { id: '378', name: 'Charcos de liquido', type: 'structure', x: 25, y: 20, width: 3, height: 1.5, category: 'hazard' },
      { id: '379', name: 'Trozos pequeños de papel', type: 'structure', x: 33, y: 24, width: 2, height: 1, category: 'detail' },
      { id: '380', name: 'Suelo sucio 1', type: 'structure', x: 4, y: 8, width: 3, height: 2, category: 'floor_detail' },
      { id: '381', name: 'Suelo sucio 2', type: 'structure', x: 12, y: 14, width: 4, height: 3, category: 'floor_detail' },
      { id: '382', name: 'Suelo sucio 3', type: 'structure', x: 22, y: 24, width: 5, height: 3, category: 'floor_detail' },
      { id: '383', name: 'Pared sucia 1', type: 'structure', x: 1, y: 8, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '384', name: 'Pared sucia 2', type: 'structure', x: 21.5, y: 11, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '385', name: 'Pared sucia 3', type: 'structure', x: 35.5, y: 10, width: 0.5, height: 4, category: 'wall_detail' },
      { id: '386', name: 'Lampara industrial 1', type: 'structure', x: 5, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '387', name: 'Lampara industrial 2', type: 'structure', x: 25, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '388', name: 'Lampara industrial 3', type: 'structure', x: 18, y: 20, width: 1.5, height: 0.7, category: 'lighting' }
    ],
    enemies: [
      { x: 5, y: 4, type: 'ranged' },
      { x: 24, y: 2, type: 'melee' },
      { x: 12, y: 10, type: 'ranged' },
      { x: 18, y: 11, type: 'melee' },
      { x: 32, y: 13, type: 'ranged' },
      { x: 10, y: 20, type: 'melee' },
      { x: 28, y: 22, type: 'ranged' }
    ]
  },
  {
    id: 12,
    name: "Fortaleza del Almacén - BOSS",
    description: "Sala final masiva con múltiples niveles, esquinas y desafíos. Enfrentamiento épico",
    playerStart: { x: 20, y: 27 },
    exit: { x: 20, y: 2 },
    walls: [
      { x: 0, y: 0, width: 40, height: 1 },
      { x: 0, y: 0, width: 1, height: 30 },
      { x: 0, y: 29, width: 40, height: 1 },
      { x: 39, y: 0, width: 1, height: 30 },
      { x: 6, y: 6, width: 8, height: 1 },
      { x: 6, y: 6, width: 1, height: 5 },
      { x: 6, y: 10, width: 5, height: 1 },
      { x: 13, y: 6, width: 1, height: 5 },
      { x: 13, y: 10, width: 5, height: 1 },
      { x: 26, y: 6, width: 8, height: 1 },
      { x: 26, y: 6, width: 1, height: 5 },
      { x: 26, y: 10, width: 5, height: 1 },
      { x: 33, y: 6, width: 1, height: 5 },
      { x: 30, y: 10, width: 4, height: 1 },
      { x: 6, y: 18, width: 8, height: 1 },
      { x: 6, y: 18, width: 1, height: 6 },
      { x: 6, y: 23, width: 5, height: 1 },
      { x: 13, y: 18, width: 1, height: 6 },
      { x: 13, y: 23, width: 5, height: 1 },
      { x: 26, y: 18, width: 8, height: 1 },
      { x: 26, y: 18, width: 1, height: 6 },
      { x: 26, y: 23, width: 5, height: 1 },
      { x: 33, y: 18, width: 1, height: 6 },
      { x: 30, y: 23, width: 4, height: 1 },
      { x: 17, y: 12, width: 6, height: 1 },
      { x: 17, y: 12, width: 1, height: 5 },
      { x: 22, y: 12, width: 1, height: 5 },
      { x: 17, y: 16, width: 6, height: 1 }
    ],
    objects: [
      { id: '389', name: 'Estanteria alta con comida 1', type: 'wall', x: 2, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '390', name: 'Estanteria alta con comida 2', type: 'wall', x: 17, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '391', name: 'Estanteria alta con comida 3', type: 'wall', x: 32, y: 1, width: 5, height: 1.5, category: 'furniture' },
      { id: '392', name: 'Estanteria metalica vacia', type: 'wall', x: 7, y: 7, width: 4, height: 1.5, category: 'furniture' },
      { id: '393', name: 'Palés apoyados a la pared', type: 'wall', x: 1, y: 8, width: 2, height: 1.5, category: 'furniture' },
      { id: '394', name: 'Tuberias vistas en la pared', type: 'wall', x: 1, y: 14, width: 0.8, height: 8, category: 'structure' },
      { id: '395', name: 'Cuadros Electicos', type: 'wall', x: 38, y: 5, width: 0.8, height: 3, category: 'structure' },
      { id: '396', name: 'Extintor con Soporte', type: 'wall', x: 38, y: 16, width: 0.8, height: 1.2, category: 'prop' },
      { id: '397', name: 'Señales de seguridad', type: 'wall', x: 19, y: 0.5, width: 1.5, height: 0.8, category: 'prop' },
      { id: '398', name: 'Puerta metalica de carga', type: 'wall', x: 18, y: 1, width: 4, height: 1, category: 'door' },
      { id: '399', name: 'Ventana alta pequeña con barrotes', type: 'wall', x: 10, y: 0.2, width: 3, height: 0.8, category: 'structure' },
      { id: '400', name: 'Columna hormigon sucios 1', type: 'wall', x: 9, y: 13, width: 2.5, height: 2.5, category: 'structure' },
      { id: '401', name: 'Columna hormigon sucios 2', type: 'wall', x: 28, y: 13, width: 2.5, height: 2.5, category: 'structure' },
      { id: '402', name: 'Columna hormigon sucios 3', type: 'wall', x: 19, y: 13, width: 2, height: 2, category: 'structure' },
      { id: '403', name: 'Caja carton vacia 1', type: 'floor', x: 4, y: 4, width: 1.5, height: 1.5, category: 'cover' },
      { id: '404', name: 'Caja carton vacia 2', type: 'floor', x: 16, y: 4, width: 1.5, height: 1.5, category: 'cover' },
      { id: '405', name: 'Caja carton vacia 3', type: 'floor', x: 35, y: 4, width: 1.5, height: 1.5, category: 'cover' },
      { id: '406', name: 'Pales madera apilados', type: 'floor', x: 3, y: 12, width: 3, height: 3, category: 'cover' },
      { id: '407', name: 'carretilla de mano', type: 'floor', x: 15, y: 8, width: 1.2, height: 1.8, category: 'obstacle' },
      { id: '408', name: 'transpaleta manual', type: 'floor', x: 24, y: 8, width: 1, height: 2.5, category: 'obstacle' },
      { id: '409', name: 'barriles / bidones', type: 'floor', x: 35, y: 12, width: 2.5, height: 2.5, category: 'cover' },
      { id: '410', name: 'Sacos harina', type: 'floor', x: 8, y: 20, width: 2, height: 2.5, category: 'cover' },
      { id: '411', name: 'Sacos azucar', type: 'floor', x: 15, y: 20, width: 2, height: 2.5, category: 'cover' },
      { id: '412', name: 'Monton de cajas', type: 'floor', x: 24, y: 20, width: 3.5, height: 3, category: 'cover' },
      { id: '413', name: 'Carros de almacen', type: 'floor', x: 30, y: 20, width: 2, height: 1.5, category: 'obstacle' },
      { id: '414', name: 'Charcos de liquido', type: 'structure', x: 11, y: 14, width: 3, height: 1.5, category: 'hazard' },
      { id: '415', name: 'Trozos pequeños de papel', type: 'structure', x: 25, y: 14, width: 2, height: 1, category: 'detail' },
      { id: '416', name: 'Suelo sucio 1', type: 'structure', x: 4, y: 8, width: 2, height: 2, category: 'floor_detail' },
      { id: '417', name: 'Suelo sucio 2', type: 'structure', x: 33, y: 8, width: 3, height: 2, category: 'floor_detail' },
      { id: '418', name: 'Suelo sucio 3', type: 'structure', x: 18, y: 24, width: 4, height: 3, category: 'floor_detail' },
      { id: '419', name: 'Pared sucia 1', type: 'structure', x: 6.5, y: 7, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '420', name: 'Pared sucia 2', type: 'structure', x: 26.5, y: 7, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '421', name: 'Pared sucia 3', type: 'structure', x: 17.5, y: 13, width: 0.5, height: 3, category: 'wall_detail' },
      { id: '422', name: 'Lampara industrial 1', type: 'structure', x: 8, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '423', name: 'Lampara industrial 2', type: 'structure', x: 28, y: 0.3, width: 1.5, height: 0.7, category: 'lighting' },
      { id: '424', name: 'Lampara industrial 3', type: 'structure', x: 20, y: 14, width: 1.5, height: 0.7, category: 'lighting' }
    ],
    enemies: [
      { x: 7, y: 8, type: 'ranged' },
      { x: 32, y: 8, type: 'ranged' },
      { x: 12, y: 14, type: 'melee' },
      { x: 27, y: 14, type: 'melee' },
      { x: 7, y: 21, type: 'ranged' },
      { x: 32, y: 21, type: 'ranged' },
      { x: 20, y: 14, type: 'melee' },
      { x: 15, y: 10, type: 'melee' },
      { x: 25, y: 10, type: 'melee' }
    ]
  }
];

